### ISSUE TITLE
1.0.0 does not build on el6 because of too old libmemcached

### ISSUE THREAD

**Issue by ingvarha** [varnish/libvmod-memcached#13]
libvmod-memcached-1.0.0 does not build on rhel6 (and clones), as the available version of libmemcached in el6 is too old.

As el6 is a supported platform for varnish, support also for libvmod-memcached should be considered.

checking for LIBMEMCACHED... no
configure: error: Package requirements (libmemcached > 0.53) were not met:
Requested 'libmemcached > 0.53' but version of libmemcached is 0.31

Ingvar

**Comment by rezan** [comment]
Can you try checking out commit 9af79f3df25c185351e8e6c603bc822bbe6135ef

**Comment by ingvarha** [comment]
Same result:

checking for LIBMEMCACHED... no
configure: error: Package requirements (libmemcached > 0.53) were not met:

Requested 'libmemcached > 0.53' but version of libmemcached is 0.31

**Comment by ingvarha** [comment]
duh, sorry, I forgot to update my build catalog. Yes, it builds fine with commit 9af79f3.

make check does not run without errors, though.

Ingvar

**Comment by rezan** [comment]
ok great, I made that commit into its own branch here:

https://github.com/varnish/libvmod-memcached/tree/4.0-el6

The reason for requiring libmemcached 1.0 or higher is due to performance. 1.0+ supports pooling and supports more of the memcached API.

Can you create a new issue for the failing tests? With the branch above, can we close this issue?

**Comment by ingvarha** [comment]
Works for me. I will try to add this as an el6 only patch to the 1.0 release, so I can have a common src.rpm for el6 and el7. I'll open a new issue for the test.
