### ISSUE TITLE
Any plans to port to Varnish 5?

### ISSUE THREAD

**Issue by therps2** [varnish/libvmod-memcached#17]
The current build system isn't compatible with Varnish 5. Any plans to port it?

**Comment by katagaStyle** [comment]
Any plans for an update?

**Comment by dridi** [comment]
Sorry for the late reply, the original maintainer of this vmod is no longer in the team. I had a look and it compiles just fine, the problem was that Varnish 5 is a bit more picky about the VMOD descriptor. This is now fixed on current master, tested with Varnish 5.1, I'm expecting it to work with 5.2.0 but please let us know if I'm wrong.
